[build]
 command = 'npm run build'
 publish = '/build'
 functions = './functions'
[functions]
  external_node_modules = ["express"]
  node_bundler = "esbuild"
[[redirects]]
 force = true
 from = '/api/*'
 to = '/.netlify/functions/api/:splat'
 status = 200

 [[redirects]]
 from = '/*'
 to = '/index.html'
 status = 200
 